modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="relicward"
version="1.0.0"
displayName="遗境守望 / Relic Ward"
logoFile="logo.png"
authors="taisuiyileba"
description='''Explore the Resonant Court, challenge the Bell Warden, shatter resonant pillars and claim personal rewards. Original two-phase boss, temple, minions, equipment and repeatable encounters.'''

[[dependencies.relicward]]
modId="forge"
mandatory=true
versionRange="[47.4.10,48)"
ordering="NONE"
side="BOTH"

[[dependencies.relicward]]
modId="curios"
mandatory=true
versionRange="[5.14.1,6)"
ordering="AFTER"
side="BOTH"

[[dependencies.relicward]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.relicward]]
modId="jade"
mandatory=false
versionRange="[11,)"
ordering="AFTER"
side="BOTH"
