package cn.suiyi.relicward.client;

import cn.suiyi.relicward.RelicWard;
import cn.suiyi.relicward.entity.BellWarden;
import net.minecraft.client.model.HierarchicalModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

/** Generated by tools/generate_model.py. Edit the shared source, not this geometry. */
public final class BellWardenModel extends HierarchicalModel<BellWarden> {
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(new ResourceLocation(RelicWard.ID, "bell_warden"), "main");
    private final ModelPart root, body, head, bell, clapper, rightArm, leftArm, rightLeg, leftLeg, rightShin, leftShin;
    private final WardenAnimator motion;

    public BellWardenModel(ModelPart baked) {
        root = baked.getChild("root");
        body = root.getChild("body");
        head = body.getChild("head");
        bell = body.getChild("bell");
        clapper = bell.getChild("clapper");
        rightArm = body.getChild("right_arm");
        leftArm = body.getChild("left_arm");
        rightLeg = root.getChild("right_leg");
        leftLeg = root.getChild("left_leg");
        rightShin = rightLeg.getChild("right_shin");
        leftShin = leftLeg.getChild("left_shin");
        motion = new WardenAnimator(root);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot().addOrReplaceChild("root", CubeListBuilder.create(),
                PartPose.offset(0.000F, 24.000F, 0.000F));
        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                /* backplate */ .texOffs(1, 1).addBox(-16.000F, -24.000F, 5.000F, 32.000F, 24.000F, 6.000F)
                /* collar_lintel */ .texOffs(167, 1).addBox(-18.000F, -27.000F, -9.000F, 36.000F, 6.000F, 20.000F)
                /* collar_shadow */ .texOffs(281, 1).addBox(-13.000F, -28.000F, -6.000F, 26.000F, 2.000F, 13.000F)
                /* lower_chest_sill */ .texOffs(361, 1).addBox(-17.000F, -3.000F, -9.000F, 34.000F, 5.000F, 19.000F)
                /* waist_joint */ .texOffs(1, 40).addBox(-10.000F, 2.000F, -5.000F, 20.000F, 4.000F, 12.000F)
                /* hip_belt */ .texOffs(67, 40).addBox(-16.000F, 5.000F, -8.000F, 32.000F, 5.000F, 18.000F)
                /* belt_boss */ .texOffs(169, 40).addBox(-5.000F, 5.000F, -10.000F, 10.000F, 6.000F, 3.000F)
                /* belt_glyph */ .texOffs(197, 40).addBox(-1.000F, 6.000F, -11.000F, 2.000F, 4.000F, 1.000F)
                /* back_stanchion_0 */ .texOffs(141, 93).addBox(-16.000F, -31.000F, 11.000F, 4.000F, 32.000F, 4.000F)
                /* back_verdig_rib_0 */ .texOffs(159, 93).addBox(-17.000F, -31.000F, 13.000F, 6.000F, 28.000F, 3.000F)
                /* back_finial_0 */ .texOffs(179, 93).addBox(-18.000F, -31.000F, 10.000F, 8.000F, 3.000F, 8.000F)
                /* back_rib_band_0 */ .texOffs(213, 93).addBox(-18.000F, -12.000F, 11.000F, 8.000F, 3.000F, 6.000F)
                /* back_stanchion_1 */ .texOffs(243, 93).addBox(-2.000F, -35.000F, 11.000F, 4.000F, 36.000F, 4.000F)
                /* back_verdig_rib_1 */ .texOffs(261, 93).addBox(-3.000F, -35.000F, 13.000F, 6.000F, 32.000F, 3.000F)
                /* back_finial_1 */ .texOffs(281, 93).addBox(-4.000F, -35.000F, 10.000F, 8.000F, 3.000F, 8.000F)
                /* back_rib_band_1 */ .texOffs(315, 93).addBox(-4.000F, -12.000F, 11.000F, 8.000F, 3.000F, 6.000F)
                /* back_stanchion_2 */ .texOffs(345, 93).addBox(12.000F, -28.000F, 11.000F, 4.000F, 29.000F, 4.000F)
                /* back_verdig_rib_2 */ .texOffs(363, 93).addBox(11.000F, -28.000F, 13.000F, 6.000F, 25.000F, 3.000F)
                /* back_finial_2 */ .texOffs(383, 93).addBox(10.000F, -28.000F, 10.000F, 8.000F, 3.000F, 8.000F)
                /* back_rib_band_2 */ .texOffs(417, 93).addBox(10.000F, -12.000F, 11.000F, 8.000F, 3.000F, 6.000F)
                /* rear_crossbeam */ .texOffs(1, 135).addBox(-21.000F, -21.000F, 10.000F, 42.000F, 4.000F, 6.000F)
                /* rear_central_seal */ .texOffs(99, 135).addBox(-6.000F, -17.000F, 15.000F, 12.000F, 12.000F, 2.000F)
                /* rear_seal_inset */ .texOffs(129, 135).addBox(-4.000F, -15.000F, 17.000F, 8.000F, 8.000F, 1.000F)
                /* rear_seal_line */ .texOffs(149, 135).addBox(-1.000F, -14.000F, 18.000F, 2.000F, 6.000F, 1.000F),
                PartPose.offset(0.000F, -40.000F, 0.000F));
        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
                /* neck_spindle */ .texOffs(193, 66).addBox(-4.000F, -1.000F, -3.000F, 8.000F, 5.000F, 8.000F)
                /* mask_core */ .texOffs(227, 66).addBox(-8.000F, -12.000F, -6.000F, 16.000F, 13.000F, 12.000F)
                /* mask_front */ .texOffs(285, 66).addBox(-7.000F, -11.000F, -8.000F, 14.000F, 11.000F, 3.000F)
                /* brow_beam */ .texOffs(321, 66).addBox(-9.000F, -12.000F, -9.000F, 18.000F, 3.000F, 3.000F)
                /* nose_ridge */ .texOffs(365, 66).addBox(-2.000F, -9.000F, -9.000F, 4.000F, 9.000F, 3.000F)
                /* eye_socket_r */ .texOffs(381, 66).addBox(-7.000F, -8.000F, -8.200F, 5.000F, 3.000F, 1.000F)
                /* eye_socket_l */ .texOffs(395, 66).addBox(2.000F, -8.000F, -8.200F, 5.000F, 3.000F, 1.000F)
                /* eye_r */ .texOffs(409, 66).addBox(-6.000F, -7.000F, -8.350F, 4.000F, 1.000F, 1.000F)
                /* eye_l */ .texOffs(421, 66).addBox(2.000F, -7.000F, -8.350F, 4.000F, 1.000F, 1.000F)
                /* jaw_mask */ .texOffs(433, 66).addBox(-6.000F, -2.000F, -8.000F, 12.000F, 4.000F, 4.000F)
                /* crown_center */ .texOffs(467, 66).addBox(-2.000F, -15.000F, -3.000F, 4.000F, 4.000F, 7.000F)
                /* ear_plate_-1 */ .texOffs(1, 93).addBox(-11.000F, -10.000F, -3.000F, 3.000F, 12.000F, 9.000F)
                /* crown_prong_-1 */ .texOffs(27, 93).addBox(-11.000F, -16.000F, -1.000F, 3.000F, 7.000F, 5.000F)
                /* crown_cap_-1 */ .texOffs(45, 93).addBox(-12.000F, -16.000F, -2.000F, 5.000F, 2.000F, 7.000F)
                /* ear_plate_1 */ .texOffs(71, 93).addBox(8.000F, -10.000F, -3.000F, 3.000F, 12.000F, 9.000F)
                /* crown_prong_1 */ .texOffs(97, 93).addBox(8.000F, -16.000F, -1.000F, 3.000F, 7.000F, 5.000F)
                /* crown_cap_1 */ .texOffs(115, 93).addBox(7.000F, -16.000F, -2.000F, 5.000F, 2.000F, 7.000F),
                PartPose.offset(0.000F, -27.000F, 0.000F));
        PartDefinition bell = body.addOrReplaceChild("bell", CubeListBuilder.create()
                /* bell_suspension */ .texOffs(281, 40).addBox(-2.000F, -1.000F, -2.000F, 4.000F, 4.000F, 4.000F)
                /* bell_crown */ .texOffs(299, 40).addBox(-4.000F, 2.000F, -4.000F, 8.000F, 3.000F, 8.000F)
                /* bell_shoulder */ .texOffs(333, 40).addBox(-6.000F, 5.000F, -5.000F, 12.000F, 4.000F, 10.000F)
                /* bell_front_wall */ .texOffs(379, 40).addBox(-7.000F, 9.000F, -6.000F, 14.000F, 6.000F, 2.000F)
                /* bell_back_wall */ .texOffs(413, 40).addBox(-7.000F, 9.000F, 4.000F, 14.000F, 6.000F, 2.000F)
                /* bell_left_wall */ .texOffs(447, 40).addBox(-7.000F, 9.000F, -4.000F, 2.000F, 6.000F, 8.000F)
                /* bell_right_wall */ .texOffs(469, 40).addBox(5.000F, 9.000F, -4.000F, 2.000F, 6.000F, 8.000F)
                /* bell_lip_front */ .texOffs(1, 66).addBox(-9.000F, 15.000F, -8.000F, 18.000F, 2.000F, 2.000F)
                /* bell_lip_back */ .texOffs(43, 66).addBox(-9.000F, 15.000F, 6.000F, 18.000F, 2.000F, 2.000F)
                /* bell_lip_left */ .texOffs(85, 66).addBox(-9.000F, 15.000F, -6.000F, 2.000F, 2.000F, 12.000F)
                /* bell_lip_right */ .texOffs(115, 66).addBox(7.000F, 15.000F, -6.000F, 2.000F, 2.000F, 12.000F)
                /* bell_crack_a */ .texOffs(145, 66).addBox(-1.000F, 7.000F, -6.150F, 1.000F, 4.000F, 1.000F)
                /* bell_crack_b */ .texOffs(151, 66).addBox(0.000F, 10.000F, -6.200F, 2.000F, 1.000F, 1.000F)
                /* bell_crack_c */ .texOffs(159, 66).addBox(1.000F, 10.000F, -6.250F, 1.000F, 5.000F, 1.000F),
                PartPose.offset(0.000F, -21.000F, -2.000F));
        PartDefinition clapper = bell.addOrReplaceChild("clapper", CubeListBuilder.create()
                /* clapper_stem */ .texOffs(165, 66).addBox(-1.000F, -2.000F, -1.000F, 2.000F, 8.000F, 2.000F)
                /* clapper_weight */ .texOffs(175, 66).addBox(-2.000F, 6.000F, -2.000F, 4.000F, 3.000F, 4.000F),
                PartPose.offset(0.000F, 10.000F, 0.000F));
        PartDefinition right_arm = body.addOrReplaceChild("right_arm", CubeListBuilder.create()
                /* right_shoulder_joint */ .texOffs(157, 135).addBox(-5.000F, -4.000F, -5.000F, 10.000F, 10.000F, 10.000F)
                /* right_pauldron */ .texOffs(199, 135).addBox(-9.000F, -7.000F, -9.000F, 18.000F, 9.000F, 18.000F)
                /* right_pauldron_crown */ .texOffs(273, 135).addBox(-8.000F, -9.000F, -7.000F, 16.000F, 3.000F, 14.000F)
                /* right_pauldron_trim */ .texOffs(335, 135).addBox(-9.000F, 1.000F, -10.000F, 18.000F, 2.000F, 20.000F)
                /* right_shoulder_glyph_top */ .texOffs(413, 135).addBox(-5.000F, -5.000F, -10.000F, 10.000F, 2.000F, 1.000F)
                /* right_shoulder_glyph_r */ .texOffs(437, 135).addBox(-5.000F, -3.000F, -10.000F, 2.000F, 3.000F, 1.000F)
                /* right_shoulder_glyph_l */ .texOffs(445, 135).addBox(3.000F, -3.000F, -10.000F, 2.000F, 3.000F, 1.000F)
                /* right_upper_arm */ .texOffs(453, 135).addBox(-5.000F, 4.000F, -5.000F, 10.000F, 12.000F, 10.000F)
                /* right_bicep_inlay */ .texOffs(495, 135).addBox(-3.000F, 6.000F, -6.000F, 6.000F, 8.000F, 1.000F),
                PartPose.offset(-22.000F, -22.000F, 0.000F));
        PartDefinition right_forearm = right_arm.addOrReplaceChild("right_forearm", CubeListBuilder.create()
                /* right_elbow */ .texOffs(1, 164).addBox(-4.000F, -2.000F, -4.000F, 8.000F, 6.000F, 8.000F)
                /* right_gauntlet */ .texOffs(35, 164).addBox(-6.000F, 3.000F, -6.000F, 12.000F, 11.000F, 12.000F)
                /* right_gauntlet_band */ .texOffs(85, 164).addBox(-7.000F, 3.000F, -7.000F, 14.000F, 3.000F, 14.000F)
                /* right_gauntlet_spine */ .texOffs(143, 164).addBox(-2.000F, 6.000F, -7.000F, 4.000F, 7.000F, 2.000F)
                /* right_wrist */ .texOffs(157, 164).addBox(-4.000F, 14.000F, -4.000F, 8.000F, 3.000F, 8.000F)
                /* right_fist */ .texOffs(191, 164).addBox(-5.000F, 16.000F, -5.000F, 10.000F, 6.000F, 10.000F)
                /* right_knuckle_-3 */ .texOffs(233, 164).addBox(-4.000F, 17.000F, -6.000F, 2.000F, 3.000F, 2.000F)
                /* right_knuckle_0 */ .texOffs(243, 164).addBox(-1.000F, 17.000F, -6.000F, 2.000F, 3.000F, 2.000F)
                /* right_knuckle_3 */ .texOffs(253, 164).addBox(2.000F, 17.000F, -6.000F, 2.000F, 3.000F, 2.000F),
                PartPose.offset(0.000F, 17.000F, 0.000F));
        PartDefinition hammer = right_forearm.addOrReplaceChild("hammer", CubeListBuilder.create()
                /* hammer_shaft */ .texOffs(439, 193).addBox(-2.000F, -20.000F, -2.000F, 4.000F, 45.000F, 4.000F)
                /* hammer_grip_top */ .texOffs(457, 193).addBox(-3.000F, -12.000F, -3.000F, 6.000F, 3.000F, 6.000F)
                /* hammer_grip_bottom */ .texOffs(483, 193).addBox(-3.000F, 7.000F, -3.000F, 6.000F, 3.000F, 6.000F)
                /* hammer_pommel */ .texOffs(1, 244).addBox(-4.000F, -23.000F, -4.000F, 8.000F, 4.000F, 8.000F)
                /* hammer_head */ .texOffs(35, 244).addBox(-7.000F, 15.000F, -12.000F, 14.000F, 11.000F, 24.000F)
                /* hammer_head_spine */ .texOffs(113, 244).addBox(-8.000F, 14.000F, -4.000F, 16.000F, 13.000F, 8.000F)
                /* hammer_face_rear */ .texOffs(163, 244).addBox(-8.000F, 16.000F, 11.000F, 16.000F, 10.000F, 4.000F)
                /* hammer_face_front */ .texOffs(205, 244).addBox(-8.000F, 16.000F, -15.000F, 16.000F, 10.000F, 4.000F)
                /* hammer_front_seal */ .texOffs(247, 244).addBox(-9.000F, 17.000F, -3.000F, 2.000F, 6.000F, 6.000F)
                /* hammer_front_glyph_v */ .texOffs(265, 244).addBox(-10.000F, 18.000F, -1.000F, 1.000F, 4.000F, 2.000F)
                /* hammer_front_glyph_h */ .texOffs(273, 244).addBox(-10.000F, 19.000F, -2.000F, 1.000F, 1.000F, 4.000F),
                PartPose.offset(0.000F, 15.000F, -1.000F));
        PartDefinition left_arm = body.addOrReplaceChild("left_arm", CubeListBuilder.create()
                /* left_shoulder_joint */ .texOffs(263, 164).addBox(-5.000F, -4.000F, -5.000F, 10.000F, 10.000F, 10.000F)
                /* left_pauldron */ .texOffs(305, 164).addBox(-9.000F, -7.000F, -9.000F, 18.000F, 9.000F, 18.000F)
                /* left_pauldron_crown */ .texOffs(379, 164).addBox(-8.000F, -9.000F, -7.000F, 16.000F, 3.000F, 14.000F)
                /* left_pauldron_trim */ .texOffs(1, 193).addBox(-9.000F, 1.000F, -10.000F, 18.000F, 2.000F, 20.000F)
                /* left_shoulder_glyph_top */ .texOffs(79, 193).addBox(-5.000F, -5.000F, -10.000F, 10.000F, 2.000F, 1.000F)
                /* left_shoulder_glyph_r */ .texOffs(103, 193).addBox(-5.000F, -3.000F, -10.000F, 2.000F, 3.000F, 1.000F)
                /* left_shoulder_glyph_l */ .texOffs(111, 193).addBox(3.000F, -3.000F, -10.000F, 2.000F, 3.000F, 1.000F)
                /* left_upper_arm */ .texOffs(119, 193).addBox(-5.000F, 4.000F, -5.000F, 10.000F, 12.000F, 10.000F)
                /* left_bicep_inlay */ .texOffs(161, 193).addBox(-3.000F, 6.000F, -6.000F, 6.000F, 8.000F, 1.000F),
                PartPose.offset(22.000F, -22.000F, 0.000F));
        PartDefinition left_forearm = left_arm.addOrReplaceChild("left_forearm", CubeListBuilder.create()
                /* left_elbow */ .texOffs(177, 193).addBox(-4.000F, -2.000F, -4.000F, 8.000F, 6.000F, 8.000F)
                /* left_gauntlet */ .texOffs(211, 193).addBox(-6.000F, 3.000F, -6.000F, 12.000F, 11.000F, 12.000F)
                /* left_gauntlet_band */ .texOffs(261, 193).addBox(-7.000F, 3.000F, -7.000F, 14.000F, 3.000F, 14.000F)
                /* left_gauntlet_spine */ .texOffs(319, 193).addBox(-2.000F, 6.000F, -7.000F, 4.000F, 7.000F, 2.000F)
                /* left_wrist */ .texOffs(333, 193).addBox(-4.000F, 14.000F, -4.000F, 8.000F, 3.000F, 8.000F)
                /* left_fist */ .texOffs(367, 193).addBox(-5.000F, 16.000F, -5.000F, 10.000F, 6.000F, 10.000F)
                /* left_knuckle_-3 */ .texOffs(409, 193).addBox(-4.000F, 17.000F, -6.000F, 2.000F, 3.000F, 2.000F)
                /* left_knuckle_0 */ .texOffs(419, 193).addBox(-1.000F, 17.000F, -6.000F, 2.000F, 3.000F, 2.000F)
                /* left_knuckle_3 */ .texOffs(429, 193).addBox(2.000F, 17.000F, -6.000F, 2.000F, 3.000F, 2.000F),
                PartPose.offset(0.000F, 17.000F, 0.000F));
        PartDefinition right_leg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                /* right_hip_joint */ .texOffs(285, 244).addBox(-5.000F, -1.000F, -5.000F, 10.000F, 5.000F, 10.000F)
                /* right_thigh */ .texOffs(327, 244).addBox(-6.000F, 3.000F, -6.000F, 12.000F, 13.000F, 12.000F)
                /* right_skirt_lamella */ .texOffs(377, 244).addBox(-7.000F, 0.000F, -9.000F, 14.000F, 10.000F, 3.000F)
                /* right_skirt_trim */ .texOffs(413, 244).addBox(-7.000F, 8.000F, -10.000F, 14.000F, 2.000F, 4.000F)
                /* right_thigh_inset */ .texOffs(451, 244).addBox(-4.000F, 11.000F, -7.000F, 8.000F, 4.000F, 2.000F),
                PartPose.offset(-10.000F, -38.000F, 0.000F));
        PartDefinition right_shin = right_leg.addOrReplaceChild("right_shin", CubeListBuilder.create()
                /* right_knee_joint */ .texOffs(473, 244).addBox(-4.000F, -2.000F, -4.000F, 8.000F, 6.000F, 8.000F)
                /* right_knee_guard */ .texOffs(1, 281).addBox(-6.000F, -1.000F, -8.000F, 12.000F, 7.000F, 3.000F)
                /* right_knee_inlay */ .texOffs(33, 281).addBox(-3.000F, 1.000F, -9.000F, 6.000F, 3.000F, 2.000F)
                /* right_shin */ .texOffs(51, 281).addBox(-6.000F, 5.000F, -4.000F, 12.000F, 8.000F, 8.000F)
                /* right_shin_spine */ .texOffs(93, 281).addBox(-2.000F, 6.000F, -5.000F, 4.000F, 6.000F, 2.000F),
                PartPose.offset(0.000F, 18.000F, 0.000F));
        PartDefinition left_leg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                /* left_hip_joint */ .texOffs(271, 281).addBox(-5.000F, -1.000F, -5.000F, 10.000F, 5.000F, 10.000F)
                /* left_thigh */ .texOffs(313, 281).addBox(-6.000F, 3.000F, -6.000F, 12.000F, 13.000F, 12.000F)
                /* left_skirt_lamella */ .texOffs(363, 281).addBox(-7.000F, 0.000F, -9.000F, 14.000F, 10.000F, 3.000F)
                /* left_skirt_trim */ .texOffs(399, 281).addBox(-7.000F, 8.000F, -10.000F, 14.000F, 2.000F, 4.000F)
                /* left_thigh_inset */ .texOffs(437, 281).addBox(-4.000F, 11.000F, -7.000F, 8.000F, 4.000F, 2.000F),
                PartPose.offset(10.000F, -38.000F, 0.000F));
        PartDefinition left_shin = left_leg.addOrReplaceChild("left_shin", CubeListBuilder.create()
                /* left_knee_joint */ .texOffs(459, 281).addBox(-4.000F, -2.000F, -4.000F, 8.000F, 6.000F, 8.000F)
                /* left_knee_guard */ .texOffs(1, 308).addBox(-6.000F, -1.000F, -8.000F, 12.000F, 7.000F, 3.000F)
                /* left_knee_inlay */ .texOffs(33, 308).addBox(-3.000F, 1.000F, -9.000F, 6.000F, 3.000F, 2.000F)
                /* left_shin */ .texOffs(51, 308).addBox(-6.000F, 5.000F, -4.000F, 12.000F, 8.000F, 8.000F)
                /* left_shin_spine */ .texOffs(93, 308).addBox(-2.000F, 6.000F, -5.000F, 4.000F, 6.000F, 2.000F),
                PartPose.offset(0.000F, 18.000F, 0.000F));
        PartDefinition right_foot = right_shin.addOrReplaceChild("right_foot", CubeListBuilder.create()
                /* right_ankle_band */ .texOffs(107, 281).addBox(-7.000F, -3.000F, -7.000F, 14.000F, 3.000F, 14.000F)
                /* right_foot */ .texOffs(165, 281).addBox(-7.000F, 0.000F, -11.000F, 14.000F, 3.000F, 18.000F)
                /* right_toe_plate */ .texOffs(231, 281).addBox(-6.000F, -1.000F, -11.000F, 12.000F, 2.000F, 7.000F),
                PartPose.offset(0.000F, 17.000F, 0.000F));
        PartDefinition left_foot = left_shin.addOrReplaceChild("left_foot", CubeListBuilder.create()
                /* left_ankle_band */ .texOffs(107, 308).addBox(-7.000F, -3.000F, -7.000F, 14.000F, 3.000F, 14.000F)
                /* left_foot */ .texOffs(165, 308).addBox(-7.000F, 0.000F, -11.000F, 14.000F, 3.000F, 18.000F)
                /* left_toe_plate */ .texOffs(231, 308).addBox(-6.000F, -1.000F, -11.000F, 12.000F, 2.000F, 7.000F),
                PartPose.offset(0.000F, 17.000F, 0.000F));
        PartDefinition chest_left = body.addOrReplaceChild("chest_left", CubeListBuilder.create()
                /* left_chest_pier */ .texOffs(79, 1).addBox(0.000F, -11.000F, -13.000F, 7.000F, 23.000F, 14.000F)
                /* chest_trim_-1 */ .texOffs(205, 40).addBox(0.000F, -10.000F, -15.000F, 4.000F, 22.000F, 2.000F)
                /* chest_stud_-1_-19 */ .texOffs(219, 40).addBox(1.000F, -7.000F, -16.000F, 2.000F, 2.000F, 1.000F)
                /* chest_stud_-1_-10 */ .texOffs(227, 40).addBox(1.000F, 2.000F, -16.000F, 2.000F, 2.000F, 1.000F)
                /* chest_rune_long_-1 */ .texOffs(235, 40).addBox(2.000F, -6.000F, -14.000F, 2.000F, 11.000F, 1.000F),
                PartPose.offset(-18.000F, -12.000F, 5.000F));
        PartDefinition chest_right = body.addOrReplaceChild("chest_right", CubeListBuilder.create()
                /* right_chest_pier */ .texOffs(123, 1).addBox(-7.000F, -11.000F, -13.000F, 7.000F, 23.000F, 14.000F)
                /* chest_trim_1 */ .texOffs(243, 40).addBox(-4.000F, -10.000F, -15.000F, 4.000F, 22.000F, 2.000F)
                /* chest_stud_1_-19 */ .texOffs(257, 40).addBox(-3.000F, -7.000F, -16.000F, 2.000F, 2.000F, 1.000F)
                /* chest_stud_1_-10 */ .texOffs(265, 40).addBox(-3.000F, 2.000F, -16.000F, 2.000F, 2.000F, 1.000F)
                /* chest_rune_long_1 */ .texOffs(273, 40).addBox(-6.000F, -6.000F, -14.000F, 2.000F, 11.000F, 1.000F),
                PartPose.offset(18.000F, -12.000F, 5.000F));
        return LayerDefinition.create(mesh, 512, 512);
    }

    @Override public ModelPart root() { return root; }

    @Override
    public void setupAnim(BellWarden entity, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        root.getAllParts().forEach(ModelPart::resetPose);
        float stride = Mth.cos(limbSwing * 0.55F);
        float walk = Math.min(limbSwingAmount, 0.8F);
        rightLeg.xRot = stride * 0.48F * walk;
        leftLeg.xRot = -stride * 0.48F * walk;
        rightShin.xRot = Math.max(0, -stride) * 0.20F * walk;
        leftShin.xRot = Math.max(0, stride) * 0.20F * walk;
        rightArm.xRot = -stride * 0.12F * walk;
        leftArm.xRot = stride * 0.32F * walk;
        rightArm.zRot = 0.035F;
        leftArm.zRot = -0.035F;
        body.y = -40.0F + Mth.sin(ageInTicks * 0.065F) * 0.12F - Math.abs(Mth.sin(limbSwing * 0.55F)) * walk * 0.4F;
        body.zRot = stride * walk * 0.018F;
        head.yRot = Mth.clamp(netHeadYaw, -35.0F, 35.0F) * Mth.DEG_TO_RAD;
        head.xRot = Mth.clamp(headPitch, -15.0F, 20.0F) * Mth.DEG_TO_RAD;
        bell.zRot = Mth.sin(ageInTicks * 0.085F) * (0.035F + walk * 0.055F);
        clapper.zRot = -Mth.sin(ageInTicks * 0.085F + 0.55F) * 0.10F;
        motion.apply(entity, ageInTicks - entity.tickCount, limbSwing, limbSwingAmount);
    }
}
