"""Regenerate 0.8.8 loot, handbell, fracture icon and tooltips after older asset passes."""
from pathlib import Path
import json
from PIL import Image,ImageDraw
ROOT=Path(__file__).resolve().parents[1]/'src/main/resources'
RESOURCES={'data/relicward/loot_tables/entities/bell_warden.json': {'type': 'minecraft:entity',
                                                          'pools': [{'rolls': 1,
                                                                     'entries': [{'type': 'minecraft:item',
                                                                                  'name': 'relicward:bell_core',
                                                                                  'functions': [{'function': 'minecraft:set_count',
                                                                                                 'count': {'type': 'minecraft:uniform',
                                                                                                           'min': 1,
                                                                                                           'max': 1}}]}]},
                                                                    {'rolls': 1,
                                                                     'entries': [{'type': 'minecraft:item',
                                                                                  'name': 'relicward:bronze_fragment',
                                                                                  'functions': [{'function': 'minecraft:set_count',
                                                                                                 'count': {'type': 'minecraft:uniform',
                                                                                                           'min': 6,
                                                                                                           'max': 8}},
                                                                                                {'function': 'minecraft:looting_enchant',
                                                                                                 'count': {'type': 'minecraft:uniform',
                                                                                                           'min': 0,
                                                                                                           'max': 1}}]}]},
                                                                    {'rolls': 1,
                                                                     'entries': [{'type': 'minecraft:item',
                                                                                  'name': 'relicward:bronze_bricks',
                                                                                  'functions': [{'function': 'minecraft:set_count',
                                                                                                 'count': {'type': 'minecraft:uniform',
                                                                                                           'min': 12,
                                                                                                           'max': 20}},
                                                                                                {'function': 'minecraft:looting_enchant',
                                                                                                 'count': {'type': 'minecraft:uniform',
                                                                                                           'min': 0,
                                                                                                           'max': 1}}]}]}]},
 'data/relicward/recipes/resonant_bell.json': {'type': 'minecraft:crafting_shaped',
                                               'pattern': [' P ', 'PAP', ' C '],
                                               'key': {'P': {'item': 'relicward:resonant_plate'},
                                                       'A': {'item': 'minecraft:amethyst_shard'},
                                                       'C': {'item': 'relicward:bell_core'}},
                                               'result': {'item': 'relicward:resonant_bell'}},
 'data/relicward/advancements/recipes/resonant_bell.json': {'parent': 'minecraft:recipes/root',
                                                            'criteria': {'has_core': {'trigger': 'minecraft:inventory_changed',
                                                                                      'conditions': {'items': [{'items': ['relicward:bell_core']}]}}},
                                                            'rewards': {'recipes': ['relicward:resonant_bell']}},
 'assets/relicward/models/item/resonant_bell.json': {'parent': 'minecraft:block/block',
                                                     'textures': {'body': 'minecraft:block/oxidized_copper',
                                                                  'trim': 'minecraft:block/copper_block',
                                                                  'particle': 'minecraft:block/copper_block'},
                                                     'elements': [{'from': [6, 11, 7],
                                                                   'to': [10, 15, 9],
                                                                   'faces': {'north': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#trim'},
                                                                             'south': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#trim'},
                                                                             'east': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'},
                                                                             'west': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'},
                                                                             'up': {'uv': [0, 0, 16, 16],
                                                                                    'texture': '#trim'},
                                                                             'down': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'}}},
                                                                  {'from': [5, 9, 5],
                                                                   'to': [11, 11, 11],
                                                                   'faces': {'north': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#body'},
                                                                             'south': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#body'},
                                                                             'east': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#body'},
                                                                             'west': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#body'},
                                                                             'up': {'uv': [0, 0, 16, 16],
                                                                                    'texture': '#body'},
                                                                             'down': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#body'}}},
                                                                  {'from': [4, 5, 4],
                                                                   'to': [12, 9, 12],
                                                                   'faces': {'north': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#body'},
                                                                             'south': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#body'},
                                                                             'east': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#body'},
                                                                             'west': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#body'},
                                                                             'up': {'uv': [0, 0, 16, 16],
                                                                                    'texture': '#body'},
                                                                             'down': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#body'}}},
                                                                  {'from': [3, 3, 3],
                                                                   'to': [13, 5, 13],
                                                                   'faces': {'north': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#trim'},
                                                                             'south': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#trim'},
                                                                             'east': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'},
                                                                             'west': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'},
                                                                             'up': {'uv': [0, 0, 16, 16],
                                                                                    'texture': '#trim'},
                                                                             'down': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'}}},
                                                                  {'from': [7, 1, 7],
                                                                   'to': [9, 5, 9],
                                                                   'faces': {'north': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#trim'},
                                                                             'south': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#trim'},
                                                                             'east': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'},
                                                                             'west': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'},
                                                                             'up': {'uv': [0, 0, 16, 16],
                                                                                    'texture': '#trim'},
                                                                             'down': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'}}},
                                                                  {'from': [5, 6, 3.8],
                                                                   'to': [11, 8, 4],
                                                                   'faces': {'north': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#trim'},
                                                                             'south': {'uv': [0, 0, 16, 16],
                                                                                       'texture': '#trim'},
                                                                             'east': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'},
                                                                             'west': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'},
                                                                             'up': {'uv': [0, 0, 16, 16],
                                                                                    'texture': '#trim'},
                                                                             'down': {'uv': [0, 0, 16, 16],
                                                                                      'texture': '#trim'}}}],
                                                     'display': {'gui': {'rotation': [25, 35, 0],
                                                                         'scale': [0.9, 0.9, 0.9]},
                                                                 'firstperson_righthand': {'rotation': [0, -25, -10],
                                                                                           'translation': [0, 1, 0],
                                                                                           'scale': [0.65, 0.65, 0.65]},
                                                                 'firstperson_lefthand': {'rotation': [0, 25, 10],
                                                                                          'translation': [0, 1, 0],
                                                                                          'scale': [0.65, 0.65, 0.65]},
                                                                 'thirdperson_righthand': {'rotation': [0, 0, 0],
                                                                                           'translation': [0, 2, 0],
                                                                                           'scale': [0.65, 0.65, 0.65]},
                                                                 'thirdperson_lefthand': {'rotation': [0, 0, 0],
                                                                                          'translation': [0, 2, 0],
                                                                                          'scale': [0.65, 0.65, 0.65]},
                                                                 'ground': {'translation': [0, 2, 0],
                                                                            'scale': [0.5, 0.5, 0.5]}}},
 'assets/relicward/models/item/echo_maul_charging.json': {'parent': 'relicward:item/echo_maul_held'}}
LANG={'en_us': {'item.relicward.resonant_bell': 'Resonant Handbell',
           'effect.relicward.armor_fracture': 'Armor Fracture',
           'tooltip.relicward.resonant_bell': 'Use on ground: a 20-block ring deals 8 damage and 8s Armor Fracture. 8s '
                                              'cooldown; costs 2 durability.',
           'tooltip.relicward.maul': '11 attack damage, 1.1 speed. Hold 0.9s: 14-damage slam in a 5-block forward '
                                     'sector, 5s Armor Fracture. 5s cooldown; early release cancels.',
           'tooltip.relicward.bell_shield': 'Block within the first 0.5s: no durability cost, cleanse Armor Fracture, '
                                            'repel nearby attacker and fracture armor for 4s. 4s cooldown.',
           'message.relicward.perfect_block': 'Perfect resonance! Armor restored; attacker repelled.',
           'message.relicward.victory': 'The bell falls silent. Loot drops on the ground; your first trophy goes to '
                                        'your inventory.',
           'advancement.relicward.victory.desc': 'Complete the court trial and collect the spoils'},
 'zh_cn': {'item.relicward.resonant_bell': '震律鸣钟',
           'effect.relicward.armor_fracture': '裂甲',
           'tooltip.relicward.resonant_bell': '站在地面右键：释放半径 20 格的钟波，造成 8 点伤害和 8 秒裂甲；冷却 8 秒，消耗 2 耐久。',
           'tooltip.relicward.maul': '11 攻击伤害，1.1 攻击速度。主手蓄力 0.9 秒自动震击：14 伤害、5 格前方范围、5 秒裂甲；冷却 5 秒。提前松开取消。',
           'tooltip.relicward.bell_shield': '举盾前 0.5 秒内成功格挡：免除本次耐久损耗、清除自身裂甲，反震近身攻击者并附加 4 秒裂甲；机制冷却 4 秒。',
           'message.relicward.perfect_block': '精准校律！裂甲净除，铜盾反震。',
           'message.relicward.victory': '钟止山息。战利品已掉落，首次奖杯自动入包；玄铎将在重鸣冷却后归位。',
           'advancement.relicward.victory.desc': '完成古庭校律并拾取战利品'}}

LANG['zh_cn']['tooltip.relicward.maul']='11 攻击伤害，1.1 攻速。蓄力 0.9 秒、落锤 0.5 秒后震击，收招 0.5 秒；14 伤害、5 格范围、5 秒裂甲，冷却 5 秒。命中前松开取消。'
LANG['en_us']['tooltip.relicward.maul']='11 damage, 1.1 speed. Charge 0.9s, downswing 0.5s, impact, recover 0.5s. 14 damage, 5-block range, 5s fracture; 5s cooldown. Release before impact to cancel.'
LANG['zh_cn']['tooltip.relicward.bell_shield']='立即起盾。'+LANG['zh_cn']['tooltip.relicward.bell_shield']
LANG['en_us']['tooltip.relicward.bell_shield']='Immediate blocking. '+LANG['en_us']['tooltip.relicward.bell_shield']
LANG['zh_cn']['message.relicward.cooldown'] = '重鸣尚需 %s 秒（持 5 块铜律碎片献纳可立即重开）。'
LANG['zh_cn']['message.relicward.need_fragments'] = '重鸣冷却中：需消耗 5 块铜律碎片方可立即重开挑战（当前持有：%s/5）。'
LANG['zh_cn']['message.relicward.fragment_restart'] = '铜律共鸣！献纳了 5 块铜律碎片，古庭重鸣，挑战再次启动！'
LANG['en_us']['message.relicward.cooldown'] = 'The next trial will be ready in %s seconds (offer 5 Bronze Fragments to restart immediately).'
LANG['en_us']['message.relicward.need_fragments'] = 'Trial on cooldown: 5 Bronze Fragments required to restart immediately (%s/5).'
LANG['en_us']['message.relicward.fragment_restart'] = 'Bronze Resonance! Offered 5 Bronze Fragments; the court tolls and the trial restarts!'

def main():
    for name,data in RESOURCES.items():
        path=ROOT/name;path.parent.mkdir(parents=True,exist_ok=True)
        path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    for lang,entries in LANG.items():
        path=ROOT/f'assets/relicward/lang/{lang}.json'
        data=json.loads(path.read_text(encoding='utf-8'));data.update(entries)
        path.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    from generate_boss_bar_and_effects import main as generate_icons
    generate_icons()
if __name__=='__main__':main()
